### ISSUE TITLE
wine require a 3G/1G user/kernel memory split

### ISSUE THREAD

**Issue by gmenga1** [AlbrechtL/RPi-QEMU-x86-wine#12]
trying to run any program (wine executable.exe) the system return the error
warning: memory above 0x80000000 doesn't seam to be accessible.
Wine requires a 3G/1G  user/kernel  memory split to work properly.
How this problem can be solved?
Does another compilation with the needed memory split exist?
Giuseppe Menga

**Comment by AlbrechtL** [comment]
It seems that you updated your kernel. The standard kernel doesn't have the "3G/1G user/kernel memory split" options enabled. Please don't update your kernel or compile it yourself with enabled "3G/1G user/kernel memory split" options

**Comment by gmenga1** [comment]
Dear Albrecht:
I'm confused about github projects and their forks.
An original project by you for rpi 2 existed from 2015 with two partial  download files:
20150924_RPi-QEMU-x86-wine.img.7z.001
20150924_RPi-QEMU-x86-wine.img.7z.002
Then a branch to your project has been done in 2017 by Mike Redrobe claiming extensions to rpi 3, with download image:
JessieQemuWine.zip

Both projects show the image of a windows notepad running on wine.
Both projects refer to
Included Software
Based on 2015-05-05-raspbian-wheezy.img
Kernel 4.1.8 with 3G/1G user/kernel memory split.

I have a new raspberry pi 3 so I downloaded the new image for rpi 3.
I didn't know anything about memory split until I read the error message.
Then, how were you and Mike able to run windows executables without that wine error?
Can you explain me the relationship between your original project an the branched one?
I thank you in advance for your interest
Giuseppe Menga

**Comment by devedse** [comment]
I'm running into the same issue:

![image](https://user-images.githubusercontent.com/2350015/33130802-ce385a7e-cf94-11e7-8ee9-b7e3d4a20cd0.png)

This is with the fresh install from Mikerr on a Raspberry PI 3

**Comment by AlbrechtL** [comment]
As I wrote above 
> It seems that you updated your kernel. The standard kernel doesn't have the "3G/1G user/kernel memory split" options enabled. Please don't update your kernel or compile it yourself with enabled "3G/1G user/kernel memory split" options

**Comment by devedse** [comment]
I used the unupdated fresh install version from Mikerr without any kernel updates. It seems that as of now, that version is not working.

I also tried your version for the RaspberryPI2 and that worked fine.

**Comment by JinxDojo** [comment]
I also experience this issue when using the [Stretch version](https://github.com/mikerr/RPi-QEMU-x86-wine) from Mikerr (which unfortunately has no Issue tracker, and Mikerr did not respond to my e-mail requesting a newer version).

I'm very new to Linux/Raspbian/Debian, so I'm really not sure I have what it takes to compile the kernel myself. Others might benefit, however, from a link on how to do that (and with what settings).

Everything was working fine for me for months, so I was very confused at why anything had changed. However, I was informed that the kernel updates with a command as simple as "upgrade". (I had thought it would take more, as I had been told upgrading from e.g. Stretch to Buster was difficult and **not** recommended.) 

Someone offered to help me try to _downgrade_ the kernel, but was confused because Raspbian doesn't seem to show anything for queries like "grep kernel /boot/config.txt" and "dpkg -l | fgrep linux-image". So, I am at a loss of what to do. It sounds like I will need to start with a fresh image, but this, too, is a pain--and I'm bound to try to "update/upgrade" again at some point. Is there a way to upgrade everything _except_ the kernel when doing "upgrade"? It seems unfortunate to be stuck in the past with everything else just so one can use QEmu+Wine.

@AlbrechtL : have you considered making a new version based on Buster or even the next iteration ("Bullseye")? This would possibly alleviate the need for "upgrade"--at least for a while.
